name: Build LaTeX PDF and diff with Pre-Preprint (v0.9)
on:
  push:
    branches:
      - main
jobs:
  build_correctness_deciders:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile bbchallenge-paper.pdf
        uses: xu-cheng/latex-action@v3
        with:
          root_file: bbchallenge-paper.tex
          work_in_root_file_dir: true
      - name: Install latexdiff
        run: sudo apt-get install latexdiff

      - name: Materialize old tag into ./old
        run: |
          git fetch --tags --force
          git worktree add --force old pre-preprint-v0.9

      - name: Flatten old and new trees
        run: |
          latexpand --keep-comments old/bbchallenge-paper.tex > old-flat.tex
          latexpand --keep-comments bbchallenge-paper.tex     > new-flat.tex

      - name: Generate redline diff with latexdiff
        run: latexdiff old-flat.tex new-flat.tex > bbchallenge-paper-diff-with-v0.9.tex

      - name: Compile diff PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: bbchallenge-paper-diff-with-v0.9.tex
          work_in_root_file_dir: true

      # (Optional) clean up the worktree
      - name: Cleanup old worktree
        if: always()
        run: git worktree remove old --force
