name: Build LaTeX PDF and diff with Pre-Preprint (v0.9)
on:
  push:
    branches:
      - main
jobs:
  build_correctness_deciders:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile bbchallenge-paper.pdf
        uses: xu-cheng/latex-action@v3
        with:
          root_file: bbchallenge-paper.tex
          work_in_root_file_dir: true
      
      - name: Install latexdiff
        run: sudo apt-get install latexdiff

      - name: Install latexpand/latexdiff
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-extra-utils

      - name: Materialize old tag into ./old
        run: |
          git fetch --tags --force
          git worktree add --force old pre-preprint-v0.9

      - name: Flatten old and new trees
        run: |
          latexpand --keep-comments bbchallenge-paper.tex     > new-flat.tex
          cd old
          latexpand --keep-comments bbchallenge-paper.tex > old-flat.tex

      - name: Generate redline diff with latexdiff
        run: latexdiff old/old-flat.tex new-flat.tex > bbchallenge-paper-diff-with-v0.9.tex

      - name: Compile diff PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: bbchallenge-paper-diff-with-v0.9.tex
          work_in_root_file_dir: true

      # (Optional) clean up the worktree
      - name: Cleanup old worktree
        if: always()
        run: git worktree remove old --force

       # Commit and push the PDFs to a dedicated branch
      - name: Commit and push both PDFs
        uses: EndBug/add-and-commit@v9
        with:
          # Add the exact files; -f keeps them even if *.pdf is in .gitignore
          add: |
            -f bbchallenge-paper.pdf
            -f bbchallenge-paper-diff-with-v0.9.pdf
          message: "chore(ci): update PDFs (main + diff vs v0.9)"
          default_author: github_actions
          new_branch: build-paper-pdf
          # You can pass custom push args; this force-updates the branch each run
          push: 'origin build-paper-pdf --set-upstream --force'