name: Build LaTeX PDF and diff with Pre-Preprint (v0.9)
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore TeX Live 2024 cache
        id: tlcache
        uses: actions/cache@v4
        with:
          path: |
            $HOME/texlive/2024
            $HOME/.texlive2024
          # tie the cache to your profile; bump if you change it
          key: texlive-2024-linux-x86_64-${{ hashFiles('.github/texlive.profile') }}
          restore-keys: |
            texlive-2024-linux-x86_64-

      - name: Install TeX Live 2024 (frozen)
        if: steps.tlcache.outputs.cache-hit != 'true'
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y perl wget xz-utils
          cd /tmp
          # ✅ correct historic path includes tlnet-final
          wget -q https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/tlnet-final/install-tl-unx.tar.gz
          tar -xzf install-tl-unx.tar.gz
          cd install-tl-20250308
          cat > profile.txt <<'EOF'
          selected_scheme scheme-full
          TEXDIR /opt/texlive/2024
          TEXMFCONFIG ~/.texlive2024/texmf-config
          TEXMFVAR ~/.texlive2024/texmf-var
          option_doc 0
          option_src 0
          EOF
          sudo ./install-tl \
            -profile profile.txt \
            -repository https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/tlnet-final

      - name: Add TeX Live 2024 to PATH
        run: echo "/opt/texlive/2024/bin/x86_64-linux" >> $GITHUB_PATH

      - name: Show TeX versions (sanity check)
        run: |
          pdftex --version
          kpsewhich --version
          latexmk -v

      - name: Build bbchallenge-paper.pdf
        run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error \
            -shell-escape bbchallenge-paper.tex
      
      - name: Install latexdiff
        run: sudo apt-get install latexdiff

      - name: Install latexpand/latexdiff
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-extra-utils

      - name: Materialize old tag into ./old
        run: |
          git fetch --tags --force
          git worktree add --force old pre-preprint-v0.9

      - name: Flatten old and new trees
        run: |
          latexpand --keep-comments bbchallenge-paper.tex     > new-flat.tex
          cd old
          latexpand --keep-comments bbchallenge-paper.tex > old-flat.tex

      - name: Generate redline diff with latexdiff
        run: latexdiff old/old-flat.tex new-flat.tex > bbchallenge-paper-diff-with-v0.9.tex

      - name: Compile diff PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: bbchallenge-paper-diff-with-v0.9.tex
          work_in_root_file_dir: true

      # (Optional) clean up the worktree
      - name: Cleanup old worktree
        if: always()
        run: git worktree remove old --force

       # Commit and push the PDFs to a dedicated branch
      - name: Commit and push both PDFs
        uses: EndBug/add-and-commit@v9
        with:
          # Add the exact files; -f keeps them even if *.pdf is in .gitignore
          add: |
            -f bbchallenge-paper.pdf
            -f bbchallenge-paper-diff-with-v0.9.pdf
          message: "chore(ci): update PDFs (main + diff vs v0.9)"
          default_author: github_actions
          new_branch: build-paper-pdf
          # You can pass custom push args; this force-updates the branch each run
          push: 'origin build-paper-pdf --set-upstream --force'